#ifndef NFT_H_GENERATED_
#define NFT_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;


static void (*Z_seal0Z_seal_hash_blake2_256Z_viii)(u32 a1, u32 a2, u32 a3);
static void (*Z_seal0Z_seal_set_storageZ_viii)(u32 a1, u32 a2, u32 a3);
static void (*Z_seal0Z_seal_value_transferredZ_vii)(u32 a1, u32 a2);
static void (*Z_seal0Z_seal_callerZ_vii)(u32 a1, u32 a2);
static u32 (*Z_seal0Z_seal_debug_messageZ_iii)(u32 a1, u32 a2);
static void (*Z_seal0Z_seal_clear_storageZ_vi)(u32 a1);
static u32 (*Z_seal0Z_seal_get_storageZ_iiii)(u32 a1, u32 a2, u32 a3);
static void (*Z_seal0Z_seal_inputZ_vii)(u32 a1, u32 a2);
static void (*Z_seal0Z_seal_returnZ_viii)(u32 a1, u32 a2, u32 a3);


extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'seal0' 'seal_hash_blake2_256' */
//extern void (*Z_seal0Z_seal_hash_blake2_256Z_viii)(u32, u32, u32);
/* import: 'seal0' 'seal_set_storage' */
//extern void (*Z_seal0Z_seal_set_storageZ_viii)(u32, u32, u32);
/* import: 'seal0' 'seal_value_transferred' */
//extern void (*Z_seal0Z_seal_value_transferredZ_vii)(u32, u32);
/* import: 'seal0' 'seal_caller' */
//extern void (*Z_seal0Z_seal_callerZ_vii)(u32, u32);
/* import: 'seal0' 'seal_debug_message' */
//extern u32 (*Z_seal0Z_seal_debug_messageZ_iii)(u32, u32);
/* import: 'seal0' 'seal_clear_storage' */
//extern void (*Z_seal0Z_seal_clear_storageZ_vi)(u32);
/* import: 'seal0' 'seal_get_storage' */
//extern u32 (*Z_seal0Z_seal_get_storageZ_iiii)(u32, u32, u32);
/* import: 'seal0' 'seal_input' */
//extern void (*Z_seal0Z_seal_inputZ_vii)(u32, u32);
/* import: 'seal0' 'seal_return' */
//extern void (*Z_seal0Z_seal_returnZ_viii)(u32, u32, u32);
/* import: 'env' 'memory' */
// extern wasm_rt_memory_t (*Z_envZ_memory);

/* export: 'deploy' */
extern void (*WASM_RT_ADD_PREFIX(Z_deployZ_vv))(void);
/* export: 'call' */
extern void (*WASM_RT_ADD_PREFIX(Z_callZ_vv))(void);
#ifdef __cplusplus
}
#endif

#endif  /* NFT_H_GENERATED_ */
